---
- name: download grafanacloud-install.sh
  when: (grafana_api_key | default(False, true)) and (grafana_id | default(False, true))
  get_url:
    url: https://raw.githubusercontent.com/grafana/agent/release/production/grafanacloud-install.sh
    dest: /tmp/
    mode: 0755

- name: excecute grafanacloud-install.sh
  when: (grafana_api_key | default(False, true)) and (grafana_id | default(False, true))
  shell: /tmp/grafanacloud-install.sh
  environment:
    ARCH: amd64
    GCLOUD_API_URL: "https://integrations-api-us-central.grafana.net"
    GCLOUD_STACK_ID: "{{ grafana_id }}"
    GCLOUD_API_KEY: "{{ grafana_api_key }}"

- name: Remove the grafanacloud-install.sh
  when: (grafana_api_key | default(False, true)) and (grafana_id | default(False, true))
  file:
    path: /tmp/grafanacloud-install.sh
    state: absent
