---
- name: Set remote
  when: git_repo | default(False, true)
  community.general.git_config:
    repo: '{{ project_path }}'
    scope: 'local'
    name: 'remote.origin.url'
    value: '{{ git_repo }}'
  ignore_errors: True

- name: Clone
  when: git_repo | default(False, true)
  ansible.builtin.git:
    repo: "{{ git_repo }}"
    dest: "{{ project_path }}"
    version: "master"
    force: yes
    accept_hostkey: yes
    depth: 1

- name: Start services
  when: git_repo | default(False, true)
  community.docker.docker_compose:
    project_src: "{{ project_path }}"
    build: yes
    pull: yes
    remove_orphans: yes
    restarted: yes
    state: present