- name: Add User
  hosts: all
  become: true # run as root
  vars_files: 
    - ../vars/all.yml

  tasks:
    - name: Ensure group "{{ GROUP }}" exists
      ansible.builtin.group:
        name: "{{ GROUP }}"
        state: present

    - name: Add the user "{{ USER }}" with group "{{ GROUP }}"
      ansible.builtin.user:
        name: "{{ USER }}"
        comment: Ansible automated user
        groups: "{{ GROUP }}"
        append: yes
        system: yes # system account
        shell: /bin/bash

    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: "{{ USER }}"
        state: present
        key: "{{ ANSIBLE_SSH_PUB_KEY }}"
      when: ANSIBLE_SSH_PUB_KEY | default('', true) | trim != ''
      ignore_errors: True # incase no ANSIBLE_SSH_PUB_KEY was set
