- name: Add User
  hosts: all
  become: true # run as root
  vars:
    USER: ansible
    GROUP: users

  tasks:
    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: "{{ USER }}"
        state: present
        key: "{{ lookup('env', 'SSH_PUB_KEY') | default(lookup('file', '~/.ssh/id_rsa.pub'), True) }}"

    - name: Ensure group "{{ GROUP }}" exists
      ansible.builtin.group:
        name: "{{ GROUP }}"
        state: present

    - name: Add the user "{{ USER }}" with group "{{ GROUP }}"
      ansible.builtin.user:
        name: "{{ USER }}"
        comment: Ansible automated user
        groups: "{{ GROUP }}"
        append: yes
        system: yes # system account
