- name: Start service
  hosts: all
  vars_files: 
    - ../vars/all.yml

  become: yes
  become_user: "{{ USER }}"
  
  tasks:
    - name: Is folder exist
      stat:
        path: "{{ PROJECT_PATH }}"
      register: is_folder_exist
    
    - name: Set remote
      when: is_folder_exist.stat.exists and GIT_REPO | default('', true) | trim != ''
      community.general.git_config:
        repo: '{{ PROJECT_PATH }}'
        scope: 'local'
        name: 'remote.origin.url'
        value: '{{ GIT_REPO }}'

    - name: Clone
      when: GIT_REPO | default('', true) | trim != ''
      ansible.builtin.git:
        repo: "{{ GIT_REPO }}"
        dest: "{{ PROJECT_PATH }}"
        force: yes
        accept_hostkey: yes
        depth: 1

    - name: Start services
      when: GIT_REPO | default('', true) | trim != ''
      community.docker.docker_compose:
        project_src: "{{ PROJECT_PATH }}"
        build: yes
        pull: yes
        remove_orphans: yes
        state: present