- name: Start service
  hosts: all
  vars:
    USER: ansible
    USER_HOME: "/home/{{ USER }}"
    PROJECT_PATH: "{{ USER_HOME }}/my-server"
    GIT_REPO: https://cjtim:{{ GIT_PASSWORD }}@github.com/cjtim/my-server.git

  become: yes
  become_user: "{{ USER }}"
  
  tasks:
    - name: Set remote
      community.general.git_config:
        repo: '{{ PROJECT_PATH }}'
        scope: 'local'
        name: 'remote.origin.url'
        value: '{{ GIT_REPO }}'
      ignore_errors: True

    - name: Clone
      ansible.builtin.git:
        repo: "{{ GIT_REPO }}"
        dest: "{{ PROJECT_PATH }}"
        force: yes
        accept_hostkey: yes
        depth: 1

    - name: Start services
      community.docker.docker_compose:
        project_src: "{{ PROJECT_PATH }}"
        build: yes
        pull: yes
        remove_orphans: yes
        state: present