name: Deploy

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: install community docker-compose plugins
        run: ansible-galaxy collection install community.docker
      
      - name: Deploy
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
          ANSIBLE_INVENTORY_BASE64: ${{ secrets.ANSIBLE_INVENTORY_BASE64 }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          ANSIBLE_SSH_PUB_KEY: ${{ secrets.ANSIBLE_SSH_PUB_KEY }}
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
        run: chmod +x ./deploy.sh && ./deploy.sh