name: Deploy

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Install community plugins
        run: |
          ansible-galaxy collection install \
          community.docker \
          community.general
      
      - name: Deploy
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
          ANSIBLE_INVENTORY_BASE64: ${{ secrets.ANSIBLE_INVENTORY_BASE64 }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          ANSIBLE_SSH_PUB_KEY: ${{ secrets.ANSIBLE_SSH_PUB_KEY }}
          GIT_REPO: "https://cjtim:${{ secrets.GIT_PASSWORD }}@github.com/cjtim/my-server.git"
        run: chmod +x ./deploy.sh && ./deploy.sh