name: Deploy

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Install community plugins
        run: |
          ansible-galaxy collection install \
          community.docker \
          community.general

      - name: Set Permission
        run: chmod +x ./deploy.sh

      - name: Install
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
          ANSIBLE_INVENTORY_BASE64: ${{ secrets.ANSIBLE_INVENTORY_BASE64 }}
          SSH_KEY: ${{ secrets.SSH_KEY }}

          ANSIBLE_SSH_PUB_KEY: ${{ secrets.ANSIBLE_SSH_PUB_KEY }}
        run: |
          ./deploy.sh playbooks/1-add-user.yml
          ./deploy.sh playbooks/2-install.yml

      - name: Start service
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
          ANSIBLE_INVENTORY_BASE64: ${{ secrets.ANSIBLE_INVENTORY_BASE64 }}
          SSH_KEY: ${{ secrets.SSH_KEY }}

          GIT_REPO: "https://cjtim:${{ secrets.GIT_PASSWORD }}@github.com/cjtim/my-server.git"
        run: ./deploy.sh playbooks/3-deploy-docker-compose.yml
